@echo off
echo Creating province folders for gallery images...

mkdir "assets\images\provinces\ha_noi"
mkdir "assets\images\provinces\hai_phong"
mkdir "assets\images\provinces\hue"
mkdir "assets\images\provinces\lai_chau"
mkdir "assets\images\provinces\quang_ninh"
mkdir "assets\images\provinces\lang_son"
mkdir "assets\images\provinces\son_la"
mkdir "assets\images\provinces\dien_bien"
mkdir "assets\images\provinces\ha_tinh"
mkdir "assets\images\provinces\nghe_an"
mkdir "assets\images\provinces\thanh_hoa"
mkdir "assets\images\provinces\bac_ninh"
mkdir "assets\images\provinces\phu_tho"
mkdir "assets\images\provinces\thai_nguyen"
mkdir "assets\images\provinces\lao_cai"
mkdir "assets\images\provinces\tuyen_quang"
mkdir "assets\images\provinces\cao_bang"
mkdir "assets\images\provinces\da_nang"
mkdir "assets\images\provinces\quang_tri"
mkdir "assets\images\provinces\ninh_binh"
mkdir "assets\images\provinces\hung_yen"
mkdir "assets\images\provinces\lam_dong"
mkdir "assets\images\provinces\khanh_hoa"
mkdir "assets\images\provinces\gia_lai"
mkdir "assets\images\provinces\quang_ngai"
mkdir "assets\images\provinces\ho_chi_minh"
mkdir "assets\images\provinces\dak_lak"
mkdir "assets\images\provinces\an_giang"
mkdir "assets\images\provinces\ca_mau"
mkdir "assets\images\provinces\dong_thap"
mkdir "assets\images\provinces\vinh_long"
mkdir "assets\images\provinces\can_tho"
mkdir "assets\images\provinces\tay_ninh"
mkdir "assets\images\provinces\dong_nai"

echo All province folders created successfully!
pause 